# Eksplorasi Dataset: Global AI Impact on Jobs (2010–2025)
Menggunakan Pandas dan Polars.

# load library

In [1]:
import pandas as pd
import numpy as np
import polars as plt




print("Library imported.")

Library imported.

# load dataset

In [2]:
df = pd.read_csv("ai_impact_jobs_2010_2025.csv")
print("Dataset imported.")

Dataset imported.

In [3]:
print("rows and columns:", df.shape)
df.head()

rows and columns: (5000, 22)

,job_id,posting_year,country,region,city,company_name,company_size,industry,job_title,seniority_level,...,ai_intensity_score,core_skills,ai_skills,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,reskilling_required,ai_job_displacement_risk,job_description_embedding_cluster,industry_ai_adoption_stage
0,836b4774-702e-49ef-93d3-2f255ce1e910,2018,Brazil,South America,London,NextGen Technologies,Small,Education,Policy Analyst,Lead,...,0.81,"Research, Project Management, Business Analysis",reinforcement learning,61586,12.68,0.11,True,Low,14,Growing
1,43699e93-7b15-4728-a4c6-9e41ff438a25,2015,UAE,Middle East,Singapore,Future Solutions,Medium,Energy,Data Scientist,Executive,...,0.04,"Research, SQL, Business Analysis, Python, Clou...",NaN,62045,-3.98,0.71,False,High,19,Emerging
2,fc9d1854-3cbf-4bab-90df-77304dfc59df,2016,Nepal,South Asia,Sydney,Future Analytics,Startup,Finance,Product Manager,Junior,...,0.15,"Statistics, Project Management, Cloud Computin...",NaN,27035,3.55,0.86,False,High,2,Emerging
3,05c1c7d3-2add-4919-91eb-f6c78bfe23d1,2015,Spain,Europe,Nairobi,Global Technologies,Large,Government,Data Scientist,Mid,...,0.19,"Cloud Computing, SQL, Project Management, Comm...",NaN,72894,-2.80,0.70,False,Low,15,Emerging
4,5e739937-d1b0-44d7-935c-7ebb3fc1f6e8,2014,Taiwan,East Asia,Sydney,Future Technologies,Small,Manufacturing,ML Engineer,Lead,...,0.11,"SQL, Python, Communication, Software Engineeri...",NaN,57215,0.85,0.87,False,High,13,Emerging

# collumn names:

In [4]:
print("Column Names:")
for col in df.columns:
    print("-", col)

Column Names:
- job_id
- posting_year
- country
- region
- city
- company_name
- company_size
- industry
- job_title
- seniority_level
- ai_mentioned
- ai_keywords
- ai_intensity_score
- core_skills
- ai_skills
- salary_usd
- salary_change_vs_prev_year_percent
- automation_risk_score
- reskilling_required
- ai_job_displacement_risk
- job_description_embedding_cluster
- industry_ai_adoption_stage

# dataset types and check missing values

In [5]:
persentase_missing = (df.isnull().sum() / len(df)) * 100
print(persentase_missing)

job_id                                 0.00
posting_year                           0.00
country                                0.00
region                                 0.00
city                                   0.00
company_name                           0.00
company_size                           0.00
industry                               0.00
job_title                              0.00
seniority_level                        0.00
ai_mentioned                           0.00
ai_keywords                           67.54
ai_intensity_score                     0.00
core_skills                            0.00
ai_skills                             67.54
salary_usd                             0.00
salary_change_vs_prev_year_percent     0.00
automation_risk_score                  0.00
reskilling_required                    0.00
ai_job_displacement_risk               0.00
job_description_embedding_cluster      0.00
industry_ai_adoption_stage             0.00
dtype: float64

In [6]:
print("dataset types: ")
df.info( )

dataset types:
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 22 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   job_id                              5000 non-null   str
 1   posting_year                        5000 non-null   int64
 2   country                             5000 non-null   str
 3   region                              5000 non-null   str
 4   city                                5000 non-null   str
 5   company_name                        5000 non-null   str
 6   company_size                        5000 non-null   str
 7   industry                            5000 non-null   str
 8   job_title                           5000 non-null   str
 9   seniority_level                     5000 non-null   str
 10  ai_mentioned                        5000 non-null   bool
 11  ai_keywords                         1623 non-null   str
 12  ai_intensity_score                  5000 non-null   float64
 13  core_skills                         5000 non-null   str
 14  ai_skills                           1623 non-null   str
 15  salary_usd                          5000 non-null   int64
 16  salary_change_vs_prev_year_percent  5000 non-null   float64
 17  automation_risk_score               5000 non-null   float64
 18  reskilling_required                 5000 non-null   bool
 19  ai_job_displacement_risk            5000 non-null   str
 20  job_description_embedding_cluster   5000 non-null   int64
 21  industry_ai_adoption_stage          5000 non-null   str
dtypes: bool(2), float64(3), int64(3), str(14)
memory usage: 791.1 KB

describe numerik

In [7]:
df.describe()

,posting_year,ai_intensity_score,salary_usd,salary_change_vs_prev_year_percent,automation_risk_score,job_description_embedding_cluster
count,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000,5000.000000
mean,2017.519400,0.287312,63096.18480,3.015192,0.586176,9.473000
std,4.638569,0.291377,31431.27151,5.968729,0.250007,5.748763
min,2010.000000,0.000000,15321.00000,-5.000000,0.100000,0.000000
25%,2013.000000,0.070000,36575.50000,-1.580000,0.330000,4.000000
50%,2017.000000,0.150000,60909.50000,1.720000,0.670000,10.000000
75%,2022.000000,0.520000,81811.75000,5.385000,0.790000,14.000000
max,2025.000000,0.950000,161547.00000,17.980000,0.900000,19.000000

describe non-numerik

In [8]:
df.drop(columns=['job_id']).describe(include='object')

C:\Users\kenne\AppData\Local\Temp\ipykernel_1888\2952501747.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.drop(columns=['job_id']).describe(include='object')

,country,region,city,company_name,company_size,industry,job_title,seniority_level,ai_keywords,core_skills,ai_skills,ai_job_displacement_risk,industry_ai_adoption_stage
count,5000,5000,5000,5000,5000,5000,5000,5000,1623,5000,1623,5000,5000
unique,44,9,14,16,5,9,10,6,617,4162,617,3,3
top,Australia,South America,Toronto,Prime Systems,Small,Tech,ML Engineer,Executive,deep learning,"SQL, Project Management, Research",deep learning,Low,Growing
freq,281,601,390,331,1031,579,558,856,72,8,72,1718,2502

# spot basic patterns (unique count)

In [9]:
unique_counts = pd.DataFrame({
    "Unique count": df.nunique(),
})
unique_counts

                                    Unique count
job_id                                      5000
posting_year                                  16
country                                       44
region                                         9
city                                          14
company_name                                  16
company_size                                   5
industry                                       9
job_title                                     10
seniority_level                                6
ai_mentioned                                   2
ai_keywords                                  617
ai_intensity_score                            77
core_skills                                 4162
ai_skills                                    617
salary_usd                                  4883
salary_change_vs_prev_year_percent          1815
automation_risk_score                         62
reskilling_required                            2
ai_job_displacement_risk                       3
job_description_embedding_cluster             20
industry_ai_adoption_stage                     3

# Isi Unique Count per Kolom

In [10]:
print("Isi (Nilai Unik) Semua Kolom:")
print("="*60)

for col in df.columns:
    unique_vals = df[col].dropna().unique()
    
    if len(unique_vals) <= 100:
        print(f"Kolom: {col} ({len(unique_vals)} nilai unik)")
        print(f"Isi: {list(unique_vals)}")
        
    else:
        print(f"Kolom: {col} ({len(unique_vals)} nilai unik)")
        print(f"Isi: [Lebih dari 100 variasi, menampilkan 10 sampel...] {list(unique_vals[:16])}")
        print("...")
        
    print("-" * 60)

Isi (Nilai Unik) Semua Kolom:
============================================================
Kolom: job_id (5000 nilai unik)
Isi: [Lebih dari 100 variasi, menampilkan 10 sampel...] ['836b4774-702e-49ef-93d3-2f255ce1e910', '43699e93-7b15-4728-a4c6-9e41ff438a25', 'fc9d1854-3cbf-4bab-90df-77304dfc59df', '05c1c7d3-2add-4919-91eb-f6c78bfe23d1', '5e739937-d1b0-44d7-935c-7ebb3fc1f6e8', '3eaa8f95-6ada-4e08-ad17-ca924707d66f', '1da6731c-2a17-4fde-b43a-3281912bc31d', '85cccc9e-f1c0-4b09-80c0-ab91b09d6f6b', '2e7cd904-6aaf-4138-9464-1ad4971c25bf', 'bcf3fde0-b3e8-457f-9b90-fa1716e92bae', '510a083d-c929-452e-bca9-2224547c3f26', 'a1d10e35-770f-4502-9e76-66b978753835', 'e39cdd94-1247-4380-89db-56c8a4b84f06', '5654e8ea-4fba-43f3-b7dc-d9d01972a6f6', '21f7cb94-8074-4252-b5cc-aff4ef10f046', 'c6e702bd-18d7-4197-a824-3e5f84e11474']
...
------------------------------------------------------------
Kolom: posting_year (16 nilai unik)
Isi: [np.int64(2018), np.int64(2015), np.int64(2016), np.int64(2014), np.int64(2022), np.int64(2017), np.int64(2023), np.int64(2011), np.int64(2012), np.int64(2019), np.int64(2025), np.int64(2010), np.int64(2020), np.int64(2021), np.int64(2013), np.int64(2024)]
------------------------------------------------------------
Kolom: country (44 nilai unik)
Isi: ['Brazil', 'UAE', 'Nepal', 'Spain', 'Taiwan', 'Colombia', 'Jordan', 'Peru', 'India', 'Sri Lanka', 'Australia', 'New Zealand', 'China', 'Netherlands', 'Pakistan', 'Kenya', 'Mexico', 'Germany', 'Indonesia', 'Argentina', 'Israel', 'Vietnam', 'Italy', 'Singapore', 'Egypt', 'South Korea', 'Canada', 'Japan', 'Bangladesh', 'Chile', 'Thailand', 'United States', 'France', 'South Africa', 'Ghana', 'Poland', 'Qatar', 'Morocco', 'Sweden', 'Philippines', 'United Kingdom', 'Nigeria', 'Saudi Arabia', 'Malaysia']
------------------------------------------------------------
Kolom: region (9 nilai unik)
Isi: ['South America', 'Middle East', 'South Asia', 'Europe', 'East Asia', 'Oceania', 'Africa', 'North America', 'Southeast Asia']
------------------------------------------------------------
Kolom: city (14 nilai unik)
Isi: ['London', 'Singapore', 'Sydney', 'Nairobi', 'Paris', 'Bangalore', 'Seoul', 'Tokyo', 'New York', 'Berlin', 'Toronto', 'Lagos', 'Dubai', 'Sao Paulo']
------------------------------------------------------------
Kolom: company_name (16 nilai unik)
Isi: ['NextGen Technologies', 'Future Solutions', 'Future Analytics', 'Global Technologies', 'Future Technologies', 'Prime Systems', 'NextGen Solutions', 'Prime Technologies', 'Global Systems', 'Global Solutions', 'Global Analytics', 'NextGen Analytics', 'Prime Solutions', 'Future Systems', 'NextGen Systems', 'Prime Analytics']
------------------------------------------------------------
Kolom: company_size (5 nilai unik)
Isi: ['Small', 'Medium', 'Startup', 'Large', 'Enterprise']
------------------------------------------------------------
Kolom: industry (9 nilai unik)
Isi: ['Education', 'Energy', 'Finance', 'Government', 'Manufacturing', 'Healthcare', 'Agriculture', 'Tech', 'Retail']
------------------------------------------------------------
Kolom: job_title (10 nilai unik)
Isi: ['Policy Analyst', 'Data Scientist', 'Product Manager', 'ML Engineer', 'Software Engineer', 'Systems Engineer', 'AI Researcher', 'Operations Manager', 'Research Scientist', 'Business Analyst']
------------------------------------------------------------
Kolom: seniority_level (6 nilai unik)
Isi: ['Lead', 'Executive', 'Junior', 'Mid', 'Senior', 'Intern']
------------------------------------------------------------
Kolom: ai_mentioned (2 nilai unik)
Isi: [np.True_, np.False_]
------------------------------------------------------------
Kolom: ai_keywords (617 nilai unik)
Isi: [Lebih dari 100 variasi, menampilkan 10 sampel...] ['reinforcement learning', 'deep learning', 'NLP, deep learning, reinforcement learning', 'machine learning', 'machine learning, NLP, deep learning', 'reinforcement learning, NLP', 'computer vision, NLP, MLOps', 'MLOps, computer vision, reinforcement learning', 'LLMs, NLP, MLOps, deep learning', 'LLMs, computer vision', 'deep learning, MLOps, computer vision', 'NLP, deep learning', 'LLMs, computer vision, NLP, deep learning', 'generative AI, deep learning, reinforcement learning', 'NLP', 'MLOps, NLP, machine learning, computer vision']
...
------------------------------------------------------------
Kolom: ai_intensity_score (77 nilai unik)
Isi: [np.float64(0.81), np.float64(0.04), np.float64(0.15), np.float64(0.19), np.float64(0.11), np.float64(0.77), np.float64(0.03), np.float64(0.44), np.float64(0.2), np.float64(0.01), np.float64(0.53), np.float64(0.09), np.float64(0.75), np.float64(0.78), np.float64(0.17), np.float64(0.02), np.float64(0.08), np.float64(0.52), np.float64(0.58), np.float64(0.06), np.float64(0.16), np.float64(0.92), np.float64(0.05), np.float64(0.1), np.float64(0.47), np.float64(0.48), np.float64(0.18), np.float64(0.85), np.float64(0.88), np.float64(0.45), np.float64(0.95), np.float64(0.07), np.float64(0.13), np.float64(0.91), np.float64(0.64), np.float64(0.41), np.float64(0.66), np.float64(0.76), np.float64(0.68), np.float64(0.46), np.float64(0.14), np.float64(0.57), np.float64(0.5), np.float64(0.93), np.float64(0.0), np.float64(0.12), np.float64(0.67), np.float64(0.56), np.float64(0.55), np.float64(0.49), np.float64(0.73), np.float64(0.43), np.float64(0.71), np.float64(0.4), np.float64(0.63), np.float64(0.62), np.float64(0.51), np.float64(0.74), np.float64(0.61), np.float64(0.42), np.float64(0.83), np.float64(0.82), np.float64(0.54), np.float64(0.89), np.float64(0.6), np.float64(0.59), np.float64(0.9), np.float64(0.94), np.float64(0.87), np.float64(0.69), np.float64(0.8), np.float64(0.84), np.float64(0.72), np.float64(0.7), np.float64(0.79), np.float64(0.65), np.float64(0.86)]
------------------------------------------------------------
Kolom: core_skills (4162 nilai unik)
Isi: [Lebih dari 100 variasi, menampilkan 10 sampel...] ['Research, Project Management, Business Analysis', 'Research, SQL, Business Analysis, Python, Cloud Computing, Data Analysis', 'Statistics, Project Management, Cloud Computing, Communication, Business Analysis', 'Cloud Computing, SQL, Project Management, Communication, Statistics, Data Analysis', 'SQL, Python, Communication, Software Engineering, Statistics, Business Analysis', 'Cloud Computing, Research, Data Analysis', 'Project Management, Python, Communication, Cloud Computing, Research', 'Software Engineering, Research, Communication, Python, SQL', 'Project Management, Software Engineering, Business Analysis, SQL, Python, Statistics', 'Data Analysis, Business Analysis, Communication, Software Engineering, Project Management, SQL', 'Business Analysis, Cloud Computing, Software Engineering', 'Data Analysis, SQL, Research', 'SQL, Research, Project Management', 'SQL, Communication, Data Analysis, Software Engineering, Business Analysis', 'Research, Python, SQL, Communication, Statistics, Software Engineering', 'Business Analysis, Python, Data Analysis, Statistics']
...
------------------------------------------------------------
Kolom: ai_skills (617 nilai unik)
Isi: [Lebih dari 100 variasi, menampilkan 10 sampel...] ['reinforcement learning', 'deep learning', 'NLP, deep learning, reinforcement learning', 'machine learning', 'machine learning, NLP, deep learning', 'reinforcement learning, NLP', 'computer vision, NLP, MLOps', 'MLOps, computer vision, reinforcement learning', 'LLMs, NLP, MLOps, deep learning', 'LLMs, computer vision', 'deep learning, MLOps, computer vision', 'NLP, deep learning', 'LLMs, computer vision, NLP, deep learning', 'generative AI, deep learning, reinforcement learning', 'NLP', 'MLOps, NLP, machine learning, computer vision']
...
------------------------------------------------------------
Kolom: salary_usd (4883 nilai unik)
Isi: [Lebih dari 100 variasi, menampilkan 10 sampel...] [np.int64(61586), np.int64(62045), np.int64(27035), np.int64(72894), np.int64(57215), np.int64(67379), np.int64(63931), np.int64(39525), np.int64(29117), np.int64(24450), np.int64(73953), np.int64(77948), np.int64(90257), np.int64(64424), np.int64(38150), np.int64(32930)]
...
------------------------------------------------------------
Kolom: salary_change_vs_prev_year_percent (1815 nilai unik)
Isi: [Lebih dari 100 variasi, menampilkan 10 sampel...] [np.float64(12.68), np.float64(-3.98), np.float64(3.55), np.float64(-2.8), np.float64(0.85), np.float64(8.47), np.float64(0.3), np.float64(1.07), np.float64(-1.7), np.float64(-0.97), np.float64(-3.34), np.float64(-4.39), np.float64(1.72), np.float64(-1.97), np.float64(5.57), np.float64(-1.46)]
...
------------------------------------------------------------
Kolom: automation_risk_score (62 nilai unik)
Isi: [np.float64(0.11), np.float64(0.71), np.float64(0.86), np.float64(0.7), np.float64(0.87), np.float64(0.29), np.float64(0.6), np.float64(0.89), np.float64(0.25), np.float64(0.75), np.float64(0.69), np.float64(0.19), np.float64(0.9), np.float64(0.2), np.float64(0.27), np.float64(0.74), np.float64(0.8), np.float64(0.77), np.float64(0.17), np.float64(0.64), np.float64(0.85), np.float64(0.88), np.float64(0.35), np.float64(0.79), np.float64(0.26), np.float64(0.4), np.float64(0.65), np.float64(0.15), np.float64(0.63), np.float64(0.67), np.float64(0.14), np.float64(0.21), np.float64(0.73), np.float64(0.76), np.float64(0.39), np.float64(0.13), np.float64(0.62), np.float64(0.22), np.float64(0.12), np.float64(0.3), np.float64(0.84), np.float64(0.23), np.float64(0.82), np.float64(0.78), np.float64(0.68), np.float64(0.61), np.float64(0.16), np.float64(0.83), np.float64(0.32), np.float64(0.72), np.float64(0.66), np.float64(0.18), np.float64(0.24), np.float64(0.34), np.float64(0.31), np.float64(0.81), np.float64(0.36), np.float64(0.38), np.float64(0.33), np.float64(0.28), np.float64(0.1), np.float64(0.37)]
------------------------------------------------------------
Kolom: reskilling_required (2 nilai unik)
Isi: [np.True_, np.False_]
------------------------------------------------------------
Kolom: ai_job_displacement_risk (3 nilai unik)
Isi: ['Low', 'High', 'Medium']
------------------------------------------------------------
Kolom: job_description_embedding_cluster (20 nilai unik)
Isi: [np.int64(14), np.int64(19), np.int64(2), np.int64(15), np.int64(13), np.int64(3), np.int64(7), np.int64(8), np.int64(6), np.int64(1), np.int64(12), np.int64(0), np.int64(5), np.int64(11), np.int64(18), np.int64(17), np.int64(9), np.int64(16), np.int64(10), np.int64(4)]
------------------------------------------------------------
Kolom: industry_ai_adoption_stage (3 nilai unik)
Isi: ['Growing', 'Emerging', 'Mature']
------------------------------------------------------------

# jumlah per kolom

In [11]:
for col in df.columns:
    if col in ["job_id"]:
        continue
    
    print(f"Kolom: {col} ({df[col].nunique()} nilai unik)")
    print("="*50)
    
    counts = df[col].value_counts()
    pct = df[col].value_counts(normalize=True).mul(100).round(1)
    
    result = pd.DataFrame({
        'Jumlah': counts,
        'Persentase (%)': pct
    })
    
    # Jika nilai unik > 20, tampilkan hanya 10 teratas & 5 terbawah
    if len(result) > 20:
        print(">> Top 10:")
        display(result.head(10))
        print(">> Bottom 5:")
        display(result.tail(5))
    else:
        display(result)
    
    print("\n")

Kolom: posting_year (16 nilai unik)
==================================================

              Jumlah  Persentase (%)
posting_year
2019             331             6.6
2025             327             6.5
2010             327             6.5
2013             326             6.5
2023             319             6.4
2014             316             6.3
2024             315             6.3
2015             312             6.2
2022             312             6.2
2016             311             6.2
2012             310             6.2
2021             309             6.2
2017             305             6.1
2020             304             6.1
2011             294             5.9
2018             282             5.6

Kolom: country (44 nilai unik)
==================================================
>> Top 10:

               Jumlah  Persentase (%)
country
Australia         281             5.6
New Zealand       255             5.1
United States     207             4.1
Mexico            193             3.9
Canada            185             3.7
Taiwan            159             3.2
Japan             138             2.8
China             137             2.7
Colombia          135             2.7
South Korea       130             2.6

>> Bottom 5:

         Jumlah  Persentase (%)
country
France       72             1.4
Italy        66             1.3
Germany      65             1.3
Poland       62             1.2
Spain        58             1.2

Kolom: region (9 nilai unik)
==================================================

                Jumlah  Persentase (%)
region
South America      601            12.0
North America      585            11.7
East Asia          564            11.3
Europe             555            11.1
Southeast Asia     549            11.0
Middle East        541            10.8
South Asia         540            10.8
Oceania            536            10.7
Africa             529            10.6

Kolom: city (14 nilai unik)
==================================================

           Jumlah  Persentase (%)
city
Toronto       390             7.8
Lagos         378             7.6
Seoul         377             7.5
Bangalore     376             7.5
London        371             7.4
Berlin        370             7.4
Nairobi       356             7.1
Tokyo         353             7.1
Sao Paulo     352             7.0
New York      348             7.0
Paris         346             6.9
Singapore     341             6.8
Dubai         330             6.6
Sydney        312             6.2

Kolom: company_name (16 nilai unik)
==================================================

                      Jumlah  Persentase (%)
company_name
Prime Systems            331             6.6
Future Systems           330             6.6
Future Solutions         322             6.4
Future Analytics         319             6.4
NextGen Solutions        317             6.3
Prime Analytics          317             6.3
Future Technologies      315             6.3
Prime Technologies       312             6.2
Global Technologies      310             6.2
Prime Solutions          310             6.2
NextGen Systems          309             6.2
NextGen Technologies     308             6.2
Global Analytics         303             6.1
Global Solutions         302             6.0
NextGen Analytics        300             6.0
Global Systems           295             5.9

Kolom: company_size (5 nilai unik)
==================================================

              Jumlah  Persentase (%)
company_size
Small           1031            20.6
Medium           998            20.0
Startup          994            19.9
Large            993            19.9
Enterprise       984            19.7

Kolom: industry (9 nilai unik)
==================================================

               Jumlah  Persentase (%)
industry
Tech              579            11.6
Manufacturing     573            11.5
Agriculture       569            11.4
Retail            567            11.3
Healthcare        560            11.2
Finance           549            11.0
Government        546            10.9
Education         535            10.7
Energy            522            10.4

Kolom: job_title (10 nilai unik)
==================================================

                    Jumlah  Persentase (%)
job_title
ML Engineer            558            11.2
Operations Manager     525            10.5
Research Scientist     520            10.4
AI Researcher          512            10.2
Systems Engineer       505            10.1
Software Engineer      492             9.8
Data Scientist         486             9.7
Policy Analyst         482             9.6
Business Analyst       480             9.6
Product Manager        440             8.8

Kolom: seniority_level (6 nilai unik)
==================================================

                 Jumlah  Persentase (%)
seniority_level
Executive           856            17.1
Senior              849            17.0
Lead                844            16.9
Junior              837            16.7
Mid                 818            16.4
Intern              796            15.9

Kolom: ai_mentioned (2 nilai unik)
==================================================

              Jumlah  Persentase (%)
ai_mentioned
False           3377            67.5
True            1623            32.5

Kolom: ai_keywords (617 nilai unik)
==================================================
>> Top 10:

                        Jumlah  Persentase (%)
ai_keywords
deep learning               72             4.4
NLP                         64             3.9
machine learning            61             3.8
reinforcement learning      60             3.7
MLOps                       54             3.3
computer vision             48             3.0
generative AI               38             2.3
LLMs                        33             2.0
NLP, MLOps                  14             0.9
deep learning, MLOps        13             0.8

>> Bottom 5:

                                                    Jumlah  Persentase (%)
ai_keywords
MLOps, reinforcement learning, machine learning          1             0.1
deep learning, LLMs, machine learning, generati...       1             0.1
reinforcement learning, computer vision, deep l...       1             0.1
computer vision, NLP, LLMs, reinforcement learning       1             0.1
NLP, deep learning, MLOps, reinforcement learning        1             0.1

Kolom: ai_intensity_score (77 nilai unik)
==================================================
>> Top 10:

                    Jumlah  Persentase (%)
ai_intensity_score
0.08                   187             3.7
0.04                   186             3.7
0.11                   184             3.7
0.16                   180             3.6
0.05                   180             3.6
0.10                   176             3.5
0.01                   175             3.5
0.02                   174             3.5
0.09                   171             3.4
0.13                   168             3.4

>> Bottom 5:

                    Jumlah  Persentase (%)
ai_intensity_score
0.70                    23             0.5
0.42                    22             0.4
0.60                    22             0.4
0.58                    21             0.4
0.40                    20             0.4

Kolom: core_skills (4162 nilai unik)
==================================================
>> Top 10:

                                                    Jumlah  Persentase (%)
core_skills
SQL, Project Management, Research                        8             0.2
SQL, Research, Software Engineering                      7             0.1
Statistics, Software Engineering, SQL                    6             0.1
Communication, Research, Project Management              6             0.1
Python, Project Management, Statistics                   6             0.1
Business Analysis, Cloud Computing, Software En...       5             0.1
Statistics, Research, Business Analysis                  5             0.1
Business Analysis, Statistics, Python                    5             0.1
Research, SQL, Software Engineering                      5             0.1
Cloud Computing, Software Engineering, Business...       5             0.1

>> Bottom 5:

                                                    Jumlah  Persentase (%)
core_skills
Communication, Cloud Computing, Python, Data An...       1             0.0
Cloud Computing, Data Analysis, Project Management       1             0.0
Software Engineering, Communication, Project Ma...       1             0.0
Project Management, Data Analysis, Business Ana...       1             0.0
SQL, Research, Cloud Computing, Communication, ...       1             0.0

Kolom: ai_skills (617 nilai unik)
==================================================
>> Top 10:

                        Jumlah  Persentase (%)
ai_skills
deep learning               72             4.4
NLP                         64             3.9
machine learning            61             3.8
reinforcement learning      60             3.7
MLOps                       54             3.3
computer vision             48             3.0
generative AI               38             2.3
LLMs                        33             2.0
NLP, MLOps                  14             0.9
deep learning, MLOps        13             0.8

>> Bottom 5:

                                                    Jumlah  Persentase (%)
ai_skills
MLOps, reinforcement learning, machine learning          1             0.1
deep learning, LLMs, machine learning, generati...       1             0.1
reinforcement learning, computer vision, deep l...       1             0.1
computer vision, NLP, LLMs, reinforcement learning       1             0.1
NLP, deep learning, MLOps, reinforcement learning        1             0.1

Kolom: salary_usd (4883 nilai unik)
==================================================
>> Top 10:

            Jumlah  Persentase (%)
salary_usd
82390            3             0.1
27035            2             0.0
32930            2             0.0
77382            2             0.0
21021            2             0.0
40159            2             0.0
90205            2             0.0
63061            2             0.0
94459            2             0.0
82883            2             0.0

>> Bottom 5:

            Jumlah  Persentase (%)
salary_usd
41317            1             0.0
37089            1             0.0
81651            1             0.0
107897           1             0.0
35755            1             0.0

Kolom: salary_change_vs_prev_year_percent (1815 nilai unik)
==================================================
>> Top 10:

                                    Jumlah  Persentase (%)
salary_change_vs_prev_year_percent
-0.67                                   11             0.2
 1.60                                   11             0.2
 0.23                                   11             0.2
-1.96                                   10             0.2
 0.69                                   10             0.2
-1.97                                    9             0.2
 2.63                                    9             0.2
 1.80                                    9             0.2
 4.70                                    9             0.2
-0.72                                    9             0.2

>> Bottom 5:

                                    Jumlah  Persentase (%)
salary_change_vs_prev_year_percent
-4.45                                    1             0.0
 10.57                                   1             0.0
 14.31                                   1             0.0
 12.19                                   1             0.0
 10.01                                   1             0.0

Kolom: automation_risk_score (62 nilai unik)
==================================================
>> Top 10:

                       Jumlah  Persentase (%)
automation_risk_score
0.86                      128             2.6
0.81                      128             2.6
0.74                      127             2.5
0.65                      127             2.5
0.67                      127             2.5
0.73                      124             2.5
0.63                      123             2.5
0.66                      123             2.5
0.75                      122             2.4
0.64                      120             2.4

>> Bottom 5:

                       Jumlah  Persentase (%)
automation_risk_score
0.37                       46             0.9
0.36                       43             0.9
0.10                       38             0.8
0.31                       37             0.7
0.40                       27             0.5

Kolom: reskilling_required (2 nilai unik)
==================================================

                     Jumlah  Persentase (%)
reskilling_required
False                  3377            67.5
True                   1623            32.5

Kolom: ai_job_displacement_risk (3 nilai unik)
==================================================

                          Jumlah  Persentase (%)
ai_job_displacement_risk
Low                         1718            34.4
Medium                      1655            33.1
High                        1627            32.5

Kolom: job_description_embedding_cluster (20 nilai unik)
==================================================

                                   Jumlah  Persentase (%)
job_description_embedding_cluster
11                                    284             5.7
12                                    278             5.6
16                                    277             5.5
2                                     268             5.4
1                                     262             5.2
15                                    261             5.2
13                                    258             5.2
8                                     257             5.1
4                                     256             5.1
10                                    253             5.1
0                                     252             5.0
19                                    247             4.9
9                                     242             4.8
3                                     237             4.7
7                                     236             4.7
5                                     229             4.6
17                                    229             4.6
6                                     227             4.5
18                                    226             4.5
14                                    221             4.4

Kolom: industry_ai_adoption_stage (3 nilai unik)
==================================================

                            Jumlah  Persentase (%)
industry_ai_adoption_stage
Growing                       2502            50.0
Emerging                      2196            43.9
Mature                         302             6.0

# purpose of the dataset

Selama periode 15 tahun, kumpulan data ini mendokumentasikan **perubahan di pasar tenaga kerja global** yang disebabkan oleh penerapan **kecerdasan buatan** di lebih dari 80 negara. Data ini menilai **risiko otomatisasi** untuk berbagai pekerjaan, mengukur perubahan dalam keterampilan inti yang dibutuhkan, dan memeriksa **dampak ekonomi** dari integrasi AI terhadap upah.

# dataset Information

[dataset link](https://www.kaggle.com/datasets/sarcasmos/ai-society)

Dataset Global AI Impact on Jobs (2010–2025) diunggah oleh user sarcasmos/Nudrat Abbas. (Kaggle)