In [1]:
import pandas as pd
import numpy as np
import polars as plt

df = pd.read_csv("ai_impact_jobs_2010_2025.csv")

# GROUPING TAHUN

## grouping geografis

negara paling banyak & paling sedikit muncul per tahun

In [6]:
df.groupby('posting_year')['country'].agg(
    jumlah='count',
    paling_banyak=lambda x: x.value_counts().idxmax(),
    paling_sedikit=lambda x: x.value_counts().idxmin(),
    median_negara=lambda x: x.value_counts().sort_values().index[len(x.value_counts()) // 2]
).reset_index()

    posting_year  jumlah  paling_banyak paling_sedikit median_negara
0           2010     327         Mexico          Spain         Chile
1           2011     294      Australia          Italy  Saudi Arabia
2           2012     310    New Zealand          Spain         India
3           2013     326         Mexico          India       Nigeria
4           2014     316    New Zealand        Germany         Italy
5           2015     312      Australia       Malaysia     Indonesia
6           2016     311      Australia          Italy         Qatar
7           2017     305  United States   South Africa   New Zealand
8           2018     282      Australia          Spain          Peru
9           2019     331      Australia         Brazil         Chile
10          2020     304  United States          Kenya      Malaysia
11          2021     309      Australia          Spain         China
12          2022     312      Australia         Brazil   Netherlands
13          2023     319    New Zealand          Italy     Indonesia
14          2024     315    New Zealand         Poland         Ghana
15          2025     327      Australia         Sweden        Brazil

region paling banyak & paling sedikit muncul per tahun

In [8]:
df.groupby('posting_year')['region'].agg(
    jumlah='count',
    paling_banyak=lambda x: x.value_counts().idxmax(),
    paling_sedikit=lambda x: x.value_counts().idxmin(),
    median_negara=lambda x: x.value_counts().sort_values().index[len(x.value_counts()) // 2]
).reset_index()

    posting_year  jumlah   paling_banyak  paling_sedikit  median_negara
0           2010     327       East Asia         Oceania    Middle East
1           2011     294       East Asia   North America         Europe
2           2012     310  Southeast Asia   North America  South America
3           2013     326   South America      South Asia    Middle East
4           2014     316   South America  Southeast Asia        Oceania
5           2015     312       East Asia  Southeast Asia  South America
6           2016     311          Europe  Southeast Asia  South America
7           2017     305     Middle East         Oceania  South America
8           2018     282          Africa  Southeast Asia         Europe
9           2019     331          Europe   North America     South Asia
10          2020     304   North America          Africa     South Asia
11          2021     309         Oceania     Middle East         Africa
12          2022     312   North America       East Asia         Africa
13          2023     319  Southeast Asia     Middle East        Oceania
14          2024     315       East Asia          Africa    Middle East
15          2025     327      South Asia  Southeast Asia  South America

kota paling banyak & paling sedikit muncul per tahun

In [11]:
df.groupby('posting_year')['city'].agg(
    jumlah='count',
    paling_banyak=lambda x: x.value_counts().idxmax(),
    paling_sedikit=lambda x: x.value_counts().idxmin(),
    median_negara=lambda x: x.value_counts().sort_values().index[len(x.value_counts()) // 2]
).reset_index()

    posting_year  jumlah paling_banyak paling_sedikit median_negara
0           2010     327     Bangalore         London       Nairobi
1           2011     294     Singapore       New York        London
2           2012     310         Tokyo          Seoul       Toronto
3           2013     326     Bangalore          Paris         Dubai
4           2014     316         Lagos         Berlin        London
5           2015     312         Seoul          Lagos        Sydney
6           2016     311         Lagos      Singapore      New York
7           2017     305        London      Bangalore         Tokyo
8           2018     282      New York          Dubai         Seoul
9           2019     331     Bangalore         Berlin       Toronto
10          2020     304         Lagos          Paris         Tokyo
11          2021     309         Seoul         Sydney         Tokyo
12          2022     312     Bangalore         Sydney       Toronto
13          2023     319         Lagos      Singapore        London
14          2024     315       Toronto          Tokyo         Dubai
15          2025     327        Berlin      Sao Paulo        Sydney

## grouping gaji

gaji usd paling banyak & paling sedikit muncul per tahun

In [13]:
df.groupby('posting_year')['salary_usd'].agg(
    jumlah='count',
    paling_banyak=lambda x: x.value_counts().idxmax(),
    paling_sedikit=lambda x: x.value_counts().idxmin(),
    median_negara=lambda x: x.value_counts().sort_values().index[len(x.value_counts()) // 2]
).reset_index()

    posting_year  jumlah  paling_banyak  paling_sedikit  median_negara
0           2010     327          39247           31284          19656
1           2011     294          31774           73953          28987
2           2012     310          21021           64424          48172
3           2013     326          61439           21542          62951
4           2014     316          57215           57215          38816
5           2015     312          82390           62045          43501
6           2016     311          27035           63931          32815
7           2017     305          29117           29117          34185
8           2018     282          61586           61586          41220
9           2019     331          97050           97050          69302
10          2020     304          78924           51789         111878
11          2021     309          50708           50708          73593
12          2022     312          67379           67379         103571
13          2023     319         145890           24450         154543
14          2024     315         126081          131923          73363
15          2025     327         102722          102722          33861

kenaikan gaji paling banyak & paling sedikit muncul per tahun

In [14]:
df.groupby('posting_year')['salary_change_vs_prev_year_percent'].agg(
    jumlah='count',
    paling_banyak=lambda x: x.value_counts().idxmax(),
    paling_sedikit=lambda x: x.value_counts().idxmin(),
    median_negara=lambda x: x.value_counts().sort_values().index[len(x.value_counts()) // 2]
).reset_index()

    posting_year  jumlah  paling_banyak  paling_sedikit  median_negara
0           2010     327          -1.97           -3.64          -4.52
1           2011     294          -1.40           -3.34          -1.07
2           2012     310          -2.73            0.04           3.58
3           2013     326           3.18            4.05          -4.07
4           2014     316          -4.47            0.85          -0.44
5           2015     312          -2.64           -3.98           2.97
6           2016     311          -3.87            3.55          -2.07
7           2017     305           1.25            1.72          -1.55
8           2018     282           1.57           12.68           7.58
9           2019     331          -0.92            5.32           6.67
10          2020     304          -3.97            9.24          16.86
11          2021     309          -1.95            6.55           2.81
12          2022     312           5.52            8.47           1.50
13          2023     319          12.01           -0.97          16.20
14          2024     315          -0.58           15.42          12.57
15          2025     327           4.48            6.80          14.60

## grouping ai adoption

penyebutan ai paling banyak & paling sedikit muncul per tahun

In [17]:
df.groupby('posting_year')['ai_mentioned'].agg(
    jumlah='count',
    paling_banyak=lambda x: x.value_counts().idxmax(),
    paling_sedikit=lambda x: x.value_counts().idxmin(),
    median_negara=lambda x: x.value_counts().sort_values().index[len(x.value_counts()) // 2]
).reset_index()

    posting_year  jumlah  paling_banyak  paling_sedikit  median_negara
0           2010     327          False            True          False
1           2011     294          False            True          False
2           2012     310          False            True          False
3           2013     326          False            True          False
4           2014     316          False            True          False
5           2015     312          False            True          False
6           2016     311          False            True          False
7           2017     305          False            True          False
8           2018     282          False            True          False
9           2019     331          False            True          False
10          2020     304          False            True          False
11          2021     309          False            True          False
12          2022     312           True           False           True
13          2023     319           True           False           True
14          2024     315           True           False           True
15          2025     327           True           False           True

tingkat intensitas ai paling banyak & paling sedikit muncul per tahun

| Skor | Interpretasi |
|:---:|:---|
| 0.00 – 0.30 | AI **sedikit** digunakan di pekerjaan tersebut |
| 0.31 – 0.60 | AI digunakan secara **moderat** |
| 0.61 – 0.95 | AI **sangat dominan** dalam pekerjaan tersebut |

In [18]:
df.groupby('posting_year')['ai_intensity_score'].agg(
    jumlah='count',
    paling_banyak=lambda x: x.value_counts().idxmax(),
    paling_sedikit=lambda x: x.value_counts().idxmin(),
    median_negara=lambda x: x.value_counts().sort_values().index[len(x.value_counts()) // 2]
).reset_index()

    posting_year  jumlah  paling_banyak  paling_sedikit  median_negara
0           2010     327           0.10            0.85           0.69
1           2011     294           0.04            0.85           0.00
2           2012     310           0.11            0.52           0.00
3           2013     326           0.13            0.42           0.70
4           2014     316           0.02            0.78           0.93
5           2015     312           0.01            0.53           0.60
6           2016     311           0.18            0.73           0.52
7           2017     305           0.05            0.93           0.59
8           2018     282           0.06            0.75           0.67
9           2019     331           0.12            0.43           0.73
10          2020     304           0.09            0.45           0.79
11          2021     309           0.11            0.91           0.78
12          2022     312           0.10            0.45           0.81
13          2023     319           0.12            0.68           0.89
14          2024     315           0.07            0.78           0.94
15          2025     327           0.45            0.56           0.82

## grouping risiko dan adaptasi

risiko otomatisasi paling banyak & paling sedikit muncul per tahun

In [19]:
df.groupby('posting_year')['automation_risk_score'].agg(
    jumlah='count',
    paling_banyak=lambda x: x.value_counts().idxmax(),
    paling_sedikit=lambda x: x.value_counts().idxmin(),
    median_negara=lambda x: x.value_counts().sort_values().index[len(x.value_counts()) // 2]
).reset_index()

    posting_year  jumlah  paling_banyak  paling_sedikit  median_negara
0           2010     327           0.86            0.30           0.79
1           2011     294           0.74            0.31           0.83
2           2012     310           0.63            0.21           0.76
3           2013     326           0.64            0.18           0.66
4           2014     316           0.79            0.31           0.60
5           2015     312           0.63            0.11           0.90
6           2016     311           0.74            0.22           0.85
7           2017     305           0.75            0.17           0.74
8           2018     282           0.86            0.60           0.21
9           2019     331           0.65            0.40           0.72
10          2020     304           0.80            0.36           0.64
11          2021     309           0.74            0.40           0.85
12          2022     312           0.30            0.85           0.15
13          2023     319           0.29            0.77           0.18
14          2024     315           0.26            0.80           0.65
15          2025     327           0.39            0.90           0.67

kebutuhan belajar skill baru paling banyak & paling sedikit muncul per tahun

In [20]:
df.groupby('posting_year')['reskilling_required'].agg(
    jumlah='count',
    paling_banyak=lambda x: x.value_counts().idxmax(),
    paling_sedikit=lambda x: x.value_counts().idxmin(),
    median_negara=lambda x: x.value_counts().sort_values().index[len(x.value_counts()) // 2]
).reset_index()

    posting_year  jumlah  paling_banyak  paling_sedikit  median_negara
0           2010     327          False            True          False
1           2011     294          False            True          False
2           2012     310          False            True          False
3           2013     326          False            True          False
4           2014     316          False            True          False
5           2015     312          False            True          False
6           2016     311          False            True          False
7           2017     305          False            True          False
8           2018     282          False            True          False
9           2019     331          False            True          False
10          2020     304          False            True          False
11          2021     309          False            True          False
12          2022     312           True           False           True
13          2023     319           True           False           True
14          2024     315           True           False           True
15          2025     327           True           False           True

Risiko Pekerjaan Digantikan oleh AI paling banyak & paling sedikit muncul per tahun

In [21]:
df.groupby('posting_year')['ai_job_displacement_risk'].agg(
    jumlah='count',
    paling_banyak=lambda x: x.value_counts().idxmax(),
    paling_sedikit=lambda x: x.value_counts().idxmin(),
    median_negara=lambda x: x.value_counts().sort_values().index[len(x.value_counts()) // 2]
).reset_index()

    posting_year  jumlah paling_banyak paling_sedikit median_negara
0           2010     327          High         Medium           Low
1           2011     294          High            Low        Medium
2           2012     310        Medium           High           Low
3           2013     326           Low           High        Medium
4           2014     316           Low           High        Medium
5           2015     312           Low         Medium          High
6           2016     311        Medium            Low          High
7           2017     305        Medium           High           Low
8           2018     282          High         Medium           Low
9           2019     331           Low           High        Medium
10          2020     304        Medium            Low          High
11          2021     309           Low           High        Medium
12          2022     312           Low         Medium          High
13          2023     319           Low         Medium          High
14          2024     315           Low         Medium          High
15          2025     327        Medium            Low          High

## grouping tren utama

In [23]:

tren_tahunan = df.groupby('posting_year').agg({
    'salary_usd': 'mean',
    'ai_intensity_score': 'mean',
    'ai_mentioned': 'mean',      
    'automation_risk_score': 'mean'
})
print(tren_tahunan)

                salary_usd  ai_intensity_score  ai_mentioned  \
posting_year
2010          47536.159021            0.158165      0.103976
2011          47875.792517            0.155306      0.098639
2012          47403.283871            0.141935      0.077419
2013          50797.125767            0.157883      0.095092
2014          54188.724684            0.205981      0.186709
2015          55694.006410            0.196635      0.169872
2016          56010.356913            0.184180      0.135048
2017          57176.445902            0.200230      0.173770
2018          65347.595745            0.320957      0.372340
2019          65798.114804            0.299789      0.350453
2020          69295.197368            0.319046      0.375000
2021          70352.906149            0.332524      0.414239
2022          76838.089744            0.459071      0.618590
2023          77788.943574            0.480219      0.636364
2024          82714.390476            0.485619      0.679365
2025          83770.201835            0.489450      0.688073

              automation_risk_score
posting_year
2010                       0.695352
2011                       0.708571
2012                       0.708000
2013                       0.704387
2014                       0.654747
2015                       0.667949
2016                       0.680225
2017                       0.658721
2018                       0.561135
2019                       0.568489
2020                       0.559211
2021                       0.538803
2022                       0.440064
2023                       0.429436
2024                       0.405079
2025                       0.408318